###

GET http://localhost:3000/menu/1

###

POST http://localhost:3000/add
Content-Type: application/json

{
  "title": "test",
  "id": 5
}

###

PUT http://localhost:3000/user

###

DELETE http://localhost:3000/deleteuser

###
GET http://localhost:3000/static
